/*
 |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
 | Author: Dominik Dancs                                                           |
 | Website: http://dodancs.moow.info                                               |
 | E-Mail: dodancs@moow.info                                                       |
 |                                                                                 |
 | Support me on Patreon: https://www.patreon.com/dodancs                          |
 |                                                                                 |
 | Copyright: 2015 Dominik Dancs & FenixPortal.eu | All rights reserved.           |
 |                                                                                 |
 | License: GNU                                                                    |
 |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
 */

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author dodan_000
 */
public class GUI_Console extends JFrame {

    //Main frame
    private JFrame gui = new JFrame(); //create JFrame gui
    
    //Settings
    private final String GUI_icon_file = "icon.png"; //gui icon file
    private final int GUI_width = 700; //gui width
    private final int GUI_height = 420; //gui height
    private final String GUI_title = "FenixLauncher - Console"; //gui title
    
    /**
     * Creates new form GUI_Console
     */
    public GUI_Console() {
        gui = new JFrame(); //create new JFrame gui
    }
    
    public void init() {
        //initComponents();
        
        //set look and feel
        try {UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());} 
        catch (UnsupportedLookAndFeelException e) {Launcher.console.error(e.toString());e.printStackTrace();}
        catch (ClassNotFoundException e) {Launcher.console.error(e.toString());e.printStackTrace();}
        catch (InstantiationException e) {Launcher.console.error(e.toString());e.printStackTrace();}
        catch (IllegalAccessException e) {Launcher.console.error(e.toString());e.printStackTrace();}
        
        guiComponents(); //init gui components
        
        gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //set default close operation

        gui.setSize(GUI_width, GUI_height); //set gui width & height
        gui.setResizable(false); //disable resizing
        gui.setLocation(0,0); //move gui to top left corner
        gui.setTitle(GUI_title); //set gui title
        gui.setIconImage(new ImageIcon(getClass().getResource(GUI_icon_file)).getImage()); //set gui icon
        
        //Generated GUI elements
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(gui.getContentPane());
        gui.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        
        pack();
        
    }
    
    public void guiComponents() { //initialize all gui components
        
        //create gui components
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        
        jTextArea1.setEditable(false); //disable text are editing
        //jTextArea1.setColumns(20); //set text area column number
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        //jTextArea1.setRows(5); //set text area row number
        jTextArea1.setBorder(null); //remove text area border
        jScrollPane1.setViewportView(jTextArea1); //add scrollbar to the text area
        
    }
    
    public void clear() {jTextArea1.setText("");} //clear text area contents
    public void append(String text) {String currentText = jTextArea1.getText(); jTextArea1.setText(currentText + "" + text);} //append text to text area
    public void appendln(String text) {String currentText = jTextArea1.getText(); jTextArea1.setText(currentText + text + System.getProperty("line.separator"));} //append text and new line to text area
    
    @Override
    public void show() {gui.setVisible(true);} //show gui
    @Override
    public void hide() {gui.setVisible(false);} //hide gui
    public void close() {gui.dispose();} //close gui

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
